### ISSUE TITLE
start route point

### ISSUE THREAD

**Issue by Micha854** [Kneckter/AutoSortCoords#1]
very nice tool, thank you very much. I have to be able to set a starting point though. is that possible somehow?

**Comment by Kneckter** [comment]
You are using the current python version? It should use the first in the list as the starting point.

**Comment by Micha854** [comment]
python 3.7 and no unfortunately it doesn't take the first point

**Comment by Kneckter** [comment]
I've made the update to set the start and/or finish points in the SpawnpointClusterTool over in [PR1](https://github.com/Kneckter/SpawnpointClusterTool/pull/1). That tool has more features but still has the basic sorting option. I'll be closing this issue and archiving this project since the other repo will include the TSP code moving forward and then I won't need to maintain two repos of the same code.
